#!/bin/bash

if [ -d ~/.config_private ]; then
   echo "~/.config_private exists. Exiting"
   exit 1
fi
if [ -d ~/.config_original ]; then
   echo "~/.config_original exists. Exiting"
   exit 1
fi

# git clone git@github.com:moisei/unix_config.git ~/.config_private
git clone https://github.com/moisei/unix_config.git ~/.config_private
if [ ! -d ~/.config_private ]; then
   echo "~/.config_private does not exist after clone. Exiting"
   exit 1
fi

mkdir ~/.config_original
if [ ! -d ~/.config_original ]; then
   echo "~/.config_original does not exist after mkdir. Exiting"
   exit 1
fi
mv ~/.profile ~/.bash_profile ~/.bashrc ~/.gitconfig ~/.config_original &> /dev/null

ln -s ~/.config_private/bash/profile ~/.profile
ln -s ~/.config_private/git/gitconfig  ~/.gitconfig
